[listen]
address = "0.0.0.0"
port = 3000

[log]
level = "info"
backups = 5
maxsize = 2147483648

[fasthttp]
concurrency = 16000
read_buffer_size = 8192
read_timeout = 300
max_requests_per_conn = 1000
reduce_memory_usage = false
